const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const path = require('node:path'); const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
function loadAuth() { const context = { URL, URLSearchParams, setTimeout, clearTimeout, Promise, Date, fetch: () => { throw new Error('unmocked'); }, chrome: {} }; vm.createContext(context); vm.runInContext(`${fs.readFileSync(path.join(root, 'background/superset-auth.js'), 'utf8')}\nglobalThis.__auth = WebSCADAAuth;`, context); return context.__auth; }
const response = (ok, body = {}, url = 'https://analytics.teias.gov.tr/api/v1/me') => ({ ok, status: ok ? 200 : 401, url, json: async () => body, text: async () => typeof body === 'string' ? body : JSON.stringify(body) });
const config = { enabled: true, baseUrl: 'https://analytics.teias.gov.tr', username: 'u', password: 'p' };
test('auth reuses a valid existing session without a login request', async () => { const auth = loadAuth(); const calls=[]; auth.__setTestDeps({ fetch: async (url) => { calls.push(url); return response(true); } }); const result = await auth.ensureSession(config); assert.equal(result.authMode, 'session'); assert.equal(calls.length, 1); });
test('direct login succeeds only after authenticated session validation', async () => { const auth = loadAuth(); let me = 0; auth.__setTestDeps({ fetch: async (url, options={}) => { if (url.includes('/api/v1/me')) return response(++me > 1); if (options.method === 'POST') return response(true, '<html>ok</html>', 'https://analytics.teias.gov.tr/'); return response(true, '<form action="/login/"><input type="hidden" name="csrf_token" value="x"><input name="username"><input type="password" name="password"></form>', 'https://analytics.teias.gov.tr/login/'); } }); const result = await auth.ensureSession(config); assert.equal(result.authMode, 'direct-login'); });
test('direct 200 without session invokes hidden-tab fallback', async () => { const auth = loadAuth(); let me = 0, executed = 0; const event = { addListener(fn){ setTimeout(() => fn(7,{status:'complete'}),0); }, removeListener(){} }; auth.__setTestDeps({ fetch: async (url, options={}) => { if (url.includes('/api/v1/me')) return response(++me >= 4); if (options.method === 'POST') return response(true, '<html>login</html>', 'https://analytics.teias.gov.tr/login/'); return response(true, '<form><input name="username"><input type="password" name="password"></form>', 'https://analytics.teias.gov.tr/login/'); }, chrome:{ tabs:{ create:async()=>({id:7}), get:async()=>({status:'complete'}), remove:async()=>{}, onUpdated:event }, scripting:{ executeScript:async()=>{ executed++; } } }, sleep:async()=>{} }); const result = await auth.ensureSession(config); assert.equal(result.authMode, 'hidden-tab'); assert.equal(executed, 1); });
test('auth failures remain AUTH_REQUIRED and source never logs credentials', async () => { const auth = loadAuth(); const event = { addListener(fn){ setTimeout(() => fn(7,{status:'complete'}),0); }, removeListener(){} }; auth.__setTestDeps({ fetch:async()=>response(false), chrome:{tabs:{create:async()=>({id:7}),get:async()=>({status:'complete'}),remove:async()=>{},onUpdated:event},scripting:{executeScript:async()=>{ throw new Error('no form'); }}}, sleep:async()=>{} }); const result=await auth.ensureSession(config); assert.equal(result.ok,false); assert.equal(result.errorType,'LOGIN_FAILED'); const source=fs.readFileSync(path.join(root,'background/superset-auth.js'),'utf8'); assert.ok(!/console\.(log|warn).*username|console\.(log|warn).*password/.test(source)); });
test('history payload preserves exact start, end and grain', () => { const context={Date}; vm.createContext(context); vm.runInContext(`${fs.readFileSync(path.join(root,'background/superset-api.js'),'utf8')}\nglobalThis.__api = WebSCADAApi;`, context); const payload=context.__api.historyPayload({}, { startTime:Date.parse('2026-08-22T08:00:00'), endTime:Date.parse('2026-08-22T16:00:00'), timeGrain:'PT5M', queryMode:'timeseries', elementNames:['P'] }, ['m1']); assert.match(payload.queries[0].time_range,/2026-08-22T08:00:00 : 2026-08-22T16:00:00/); assert.equal(payload.queries[0].time_grain_sqla,'PT5M'); });
test('canonical resolver keeps multi-terminal line IDs and never uses topology ID', () => { const r=require('../core/entity-resolver.js'); const line={kind:'hat',id:'topology-id',scada:{active:{ids:['p1','p2']},reactive:{ids:['q1','q2']}}}; assert.deepEqual(r.resolveMeasurementIds(line,['P','Q'],[]),['p1','p2','q1','q2']); });
test('pagination and query guardrail bound workspace loads', () => { const u=require('../core/workspace-utils.js'); assert.deepEqual(u.pageSlice(Array.from({length:120}),2,50).rows.length,50); assert.equal(u.autoGrain(0,24*3600000),'PT5M'); assert.equal(u.guardrail(300,0,7*86400000,'PT1M').ok,false); });
test('worker keeps live, history, snapshot and workspace message semantics separate', () => { const source=fs.readFileSync(path.join(root,'background/service-worker.js'),'utf8'); assert.match(source,/SCADA_FETCH: WebSCADAQuery\.executeLiveScada/); assert.match(source,/SCADA_HISTORY_FETCH: WebSCADAQuery\.executeHistorySeries/); assert.match(source,/SCADA_HISTORICAL_SNAPSHOT_FETCH: WebSCADAQuery\.executeHistoricalSnapshot/); assert.match(source,/WEBSCADA_QUERY: WebSCADAQuery\.executeWorkspaceQuery/); });
test('snapshot helper selects the newest row at or before selected instant', () => { const source=fs.readFileSync(path.join(root,'background/query-service.js'),'utf8'); const context={WebSCADAAuth:{},WebSCADAApi:{},chrome:{runtime:{sendMessage:()=>({catch(){}})}}}; vm.createContext(context); vm.runInContext(`${source}\nglobalThis.__query=WebSCADAQuery;`,context); const at=Date.parse('2026-08-22T16:00:00Z'); const rows=[{sinsid:'a',elementName:'P',__time:'2026-08-22T15:59:00Z'},{sinsid:'a',elementName:'P',__time:'2026-08-22T16:01:00Z'},{sinsid:'a',elementName:'Q',__time:'2026-08-22T15:58:00Z'}]; const picked=context.__query.pickSnapshot(rows,at,['a']); assert.equal(picked.length,2); assert.equal(picked[0].__time,'2026-08-22T15:59:00Z'); });
